# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]
# Site settings
title: Harbor
description: "All-in-one 401(k) plan"
keywords: affordable, modern, 401(k), retirement, full-service, automated, retirement, pre-tax, auto-enrollment, HR-tech, Fintech, Chicago, Illinois, mobile, compliance, fiduciary
email: tripathi@vesthq.com
url: http://www.harborhq.com
repository: https://github.com/VestHQ/Harbor
google_analytics: UA-122850848-1


plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 6 versions